trigger:
  - master

variables:
  - name: 'System.Debug'
    value: 'true'

stages:
  - stage: 'Set_variable_stage'
    displayName: 'Set_variable_stage'
    jobs:
      - job: 'Set_variable_job'
        displayName: 'Set_variable_job'
        pool:
          vmImage: ubuntu-latest

        steps:
          - bash: |
              MY_VARIABLE="this is my variable"
              echo "##vso[task.setvariable variable=GLOBAL_VAR;isOutput=true]$MY_VARIABLE"
            name: SetVariableStep

      - job: 'Get_variable_job'
        displayName: 'Get_variable_job'
        dependsOn: Set_variable_job
        pool:
          vmImage: ubuntu-latest
        variables:
          GetVariableFromStage: $[ stageDependencies.Set_variable_stage.Set_variable_job.outputs['SetVariableStep.GLOBAL_VAR'] ]

        steps:
          - bash: |
              echo $(GetVariableFromStage)
